### PR TITLE
Move migration guide message

### PR DESCRIPTION
**Pull request by adamvoss**
The introduced header seemed out of place and appeared "below the fold." This gives it a more prominent position.

### CODE REVIEW

**Comment by handrews** [comment]
Hmm... My goal was specifically to make it its own section for visibility.  Lemme download this and poke at it, I might come around to this approach.

**Comment by adamvoss** [comment]
This tries to do the same with bolding and placement.

If you don't like it, my next suggestion would be to change the heading to `Migration guides` and put a table below it to match the rest of the sections.  In this case it would probably also move the links on Specification Links page in the Draft-06 section to their own bullet points rather than parenthetical links.

**Comment by handrews** [comment]
@adamvoss good ideas.  I will play around with them.  I'm otherwise mostly waiting for feedback on spec PRs at this point.  I still don't want to get into the administrative stuff that I earlier said needed input from other team members, but I have a bit more bandwidth to think about this sort of thing for a few days.

Once the spec is in final review, we should definitely revisit the release process stuff and other concerns you raised a while back.

**Comment by handrews** [comment]
See the original PR for what I chose to do- I did incorporate some ideas from this.

**Pull request closed without merging**
